config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, 
    presence: true,
    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # 記事の一覧表示
  def index
    @articles = Article.all
  end
  
  # 記事の表示
  def show
    @article = Article.find(params[:id])
  end
  
  # 記事の作成
  def new 
    @article = Article.new
  end
  
  # 記事の登録
  def create
    # articleモデルの属性の初期化
    @article = Article.new(article_params)

    # DBに登録できた場合
    if @article.save
        # 記事ページに遷移する
        redirect_to @article
    # DBに登録できなかった場合
    else
        # 作成ページに遷移する
        render 'new'
    end
  end

  # コントローラパラメータの定義
  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
  
  # 記事の編集
  def edit
    @article = Article.find(params[:id])
  end
  
  # 記事の更新
  def update
    @article = Article.find(params[:id])

    # DBに登録できた場合
    if @article.update(article_params)
        # 記事ページに遷移する
        redirect_to @article
    # DBに登録できなかった場合
    else
        # 編集ページに遷移する
        render 'edit'
    end
  end
  
  # 記事の削除
  def destroy
    @article = Article.find(params[:id])

    # 記事の削除
    @article.destroy
   
    # TOPページに遷移する
    redirect_to articles_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= form_with(model: @article, local: true) do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<table>
  <tr>
    <th>title</th>
    <th>text</th>
    <th colspan="3"></th>
  </tr>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@article.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>